spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autoconfiguration
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#  jackson:
#    serialization:
#      fail-on-empty-beans: false #빈값은 직렬화하지 않음


server:
  port: 8081

debug: true